using System;

namespace Pactas.SDK.DTO
{
    /// <summary>
    /// Two-Letter country codes (hopefully) according to ISO 3166
    /// Updated 2013-10-22, synchronized to static CountryList
    /// </summary>
    public enum Iso3166Country
    {
        AF, AX, AL, DZ, AS, AD, AO, AI, AQ, AG, AR, AM, AW, AU, AT, AZ, BS, BH, BD, 
        BB, BY, BE, BZ, BJ, BM, BT, BO, BQ, BA, BW, BV, BR, IO, BN, BG, BF, BI, KH, 
        CM, CA, CV, KY, CF, TD, CL, CN, CX, CC, CO, KM, CG, CD, CK, CR, CI, HR, CU, 
        CW, CY, CZ, DK, DJ, DM, DO, EC, EG, SV, GQ, ER, EE, ET, FK, FO, FJ, FI, FR, 
        GF, PF, TF, GA, GM, GE, DE, GH, GI, GR, GL, GD, GP, GU, GT, GG, GN, GW, GY, 
        HT, HM, VA, HN, HK, HU, IS, IN, ID, IR, IQ, IE, IM, IL, IT, JM, JP, JE, JO, 
        KZ, KE, KI, KP, KR, KW, KG, LA, LV, LB, LS, LR, LY, LI, LT, LU, MO, MK, MG, 
        MW, MY, MV, ML, MT, MH, MQ, MR, MU, YT, MX, FM, MD, MC, MN, ME, MS, MA, MZ,
        MM, NA, NR, NP, NL, NC, NZ, NI, NE, NG, NU, NF, MP, NO, OM, PK, PW, PS, PA, 
        PG, PY, PE, PH, PN, PL, PT, PR, QA, RE, RO, RU, RW, BL, SH, KN, LC, MF, PM, 
        VC, WS, SM, ST, SA, SN, RS, SC, SL, SG, SX, SK, SI, SB, SO, ZA, GS, SS, ES, 
        LK, SD, SR, SJ, SZ, SE, CH, SY, TW, TJ, TZ, TH, TL, TG, TK, TO, TT, TN, TR, 
        TM, TC, TV, UG, UA, AE, GB, US, UM, UY, UZ, VU, VE, VN, VG, VI, WF, EH, YE, 
        ZM, ZW
    }

    /// <summary>
    /// Two-letter language codes (hopefully) according to ISO 639-1
    /// NOTE: About 40 must be missing from this list!
    /// </summary>
    [Obsolete("Incomplete, inconsistent. Use a string instead and validate it using LanguageList")]
    public enum Language { _c = 0, ab, af, an, ar, @as, az, be, bg, bn, bo, br, bs, ca, ce, co, cs, cu, cy, da, de, el, en, eo, es, et, eu, fa, fi, fj, fo, fr, fy, ga, gd, gl, gv, he, hi, hr, ht, hu, hy, id, @is, it, ja, jv, ka, kg, ko, ku, kw, ky, la, lb, li, ln, lt, lv, mg, mk, mn, mo, ms, mt, my, nb, ne, nl, nn, no, oc, pl, pt, rm, ro, ru, sc, se, sk, sl, so, sq, sr, sv, sw, tk, tr, ty, uk, ur, uz, vi, vo, yi, zh };

    /// <summary>
    /// Three-letter currency codes (hopefully) according to ISO 4217
    /// Note: The numerical values are the respective ISO currency codes
    /// </summary>
    public enum Currency
    {
        AED = 784,
        AFN = 971,
        ALL = 8,
        AMD = 51,
        ANG = 532,
        AOA = 973,
        ARS = 32,
        AUD = 36,
        AWG = 533,
        AZN = 944,
        BAM = 977,
        BBD = 52,
        BDT = 50,
        BGN = 975,
        BHD = 48,
        BIF = 108,
        BND = 96,
        BOB = 68,
        BOV = 984,
        BRL = 986,
        BSD = 44,
        BTN = 64,
        BWP = 72,
        BYR = 974,
        BZD = 84,
        CAD = 124,
        CDF = 976,
        CHF = 756,
        CLP = 152,
        CNY = 156,
        COP = 170,
        COU = 970,
        CRC = 188,
        CUC = 931,
        CUP = 192,
        CVE = 132,
        CZK = 203,
        DJF = 262,
        DKK = 208,
        DOP = 214,
        DZD = 12,
        EEK = 233,
        EGP = 818,
        ERN = 232,
        ETB = 230,
        EUR = 978,
        FJD = 242,
        FKP = 238,
        GBP = 826,
        GEL = 981,
        GHS = 936,
        GIP = 292,
        GMD = 270,
        GNF = 324,
        GTQ = 320,
        GYD = 328,
        HKD = 344,
        HNL = 340,
        HRK = 191,
        HTG = 332,
        HUF = 348,
        IDR = 360,
        ILS = 376,
        INR = 356,
        IQD = 368,
        IRR = 364,
        JMD = 388,
        JOD = 400,
        JPY = 392,
        KES = 404,
        KGS = 417,
        KHR = 116,
        KMF = 174,
        KPW = 408,
        KRW = 410,
        KWD = 414,
        KYD = 136,
        KZT = 398,
        LAK = 418,
        LBP = 422,
        LKR = 144,
        LRD = 430,
        LSL = 426,
        LTL = 440,
        LVL = 428,
        LYD = 434,
        MAD = 504,
        MDL = 498,
        MKD = 807,
        MMK = 104,
        MNT = 496,
        MOP = 446,
        MUR = 480,
        MVR = 462,
        MWK = 454,
        MXN = 484,
        MYR = 458,
        MZN = 943,
        NAD = 516,
        NGN = 566,
        NIO = 558,
        NOK = 578,
        NPR = 524,
        NZD = 554,
        OMR = 512,
        PAB = 590,
        PEN = 604,
        PGK = 598,
        PHP = 608,
        PKR = 586,
        PLN = 985,
        QAR = 634,
        RON = 946,
        RSD = 941,
        RUB = 643,
        RWF = 646,
        SAR = 682,
        SBD = 90,
        SCR = 690,
        SDG = 938,
        SEK = 752,
        SGD = 702,
        SHP = 654,
        SLL = 694,
        SOS = 706,
        SRD = 968,
        SYP = 760,
        SZL = 748,
        THB = 764,
        TJS = 972,
        TMT = 934,
        TND = 788,
        TRY = 949,
        TTD = 780,
        TWD = 901,
        TZS = 834,
        UAH = 980,
        UGX = 800,
        USD = 840,
        USN = 997,
        USS = 998,
        UYU = 858,
        UZS = 860,
        VUV = 548,
        WST = 882,
        XAF = 950,
        XCD = 951,
        XOF = 952,
        XPF = 953,
        YER = 886,
        ZAR = 710,
        ZMK = 894,
        ZWL = 932
    }
}
